### ISSUE TITLE
use in combination with LightGallery

### ISSUE THREAD

**Issue by FreederFree** [magespecialist/m2_MSP_LightSlider#1]
Hey there, how can I use your module in combination with LightGallery?

The official documentation suports the following:

```javascript
onSliderLoad: function(el) {
    el.lightGallery({
        selector: '#imageGallery .lslide'
     });
});
```

How can I achive this using x-magento-init syntax?

**Comment by slackerzz** [comment]
I think that in this case you should use [imperative notation](http://devdocs.magento.com/guides/v2.1/javascript-dev-guide/javascript/js_init.html#init_script), so following their [example](http://sachinchoolur.github.io/lightslider/examples.html), instead of a ```<script type="text/x-magento-init">...</script>``` try:

```
<script>
    require([
        'jquery',
        'LightGallery',
        'LightSlider'
    ], function($){
        $(document).ready(function() {
        $('#imageGallery').lightSlider({
            gallery:true,
            item:1,
            loop:true,
            thumbItem:9,
            slideMargin:0,
            enableDrag: false,
            currentPagerPosition:'left',
            onSliderLoad: function(el) {
                el.lightGallery({
                    selector: '#imageGallery .lslide'
                });
            }   
        });  
      });
    });
</script>
```
